from app.models.userTypeGym import UserTypeGym
from app.models.usertype import UserType
from app.models.user import User
from app.models.user_trophy import UserTrophy
from app.models.trophy import Trophy
from app.models.training_plan import TrainingPlan
from app.models.session import Session
from app.models.routine import Routine
from app.models.routine_schedule import RoutineSchedule
from app.models.routine_exercise import RoutineExercise
from app.models.request import Request
from app.models.request_type import RequestType
from app.models.request_status import RequestStatus
from app.models.request_receiver import RequestReceiver
from app.models.recipeIngredient import RecipeIngredient
from app.models.recipe import Recipe
from app.models.post import Post
from app.models.notification import Notification
from app.models.notification_user import notification_user
from app.models.muscle import Muscle
from app.models.mealSchedule import MealSchedule
from app.models.ingredient import Ingredient
from app.models.gym import Gym
from app.models.comment import Comment
from app.models.exercise import Exercise

